apiVersion: apps/v1
kind: Deployment
metadata:
  name: gatewayserver
  labels:
    app: gatewayserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gatewayserver
  template:
    metadata: 
      labels:
        app: gatewayserver
    spec: 
      containers:
        - name: gatewayserver
          image: robindocker/microservice_gatewayserver:1.0.0
          ports:
          - containerPort: 8072
          env:
          - name: SPRING_PROFILES_ACTIVE
            valueFrom:
              configMapKeyRef: 
                name: microservicios-configmap
                key: spring_profiles_active
          - name: SPRING_CONFIG_IMPORT
            valueFrom:
              configMapKeyRef: 
                name: microservicios-configmap
                key: spring_config_config_import  
          - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
            valueFrom:
              configMapKeyRef: 
                name: microservicios-configmap
                key: eureka_client_serviceurl_defaultzone  
     
---
apiVersion: v1
kind: Service
metadata:
  name: gatewayserver-service
spec:
  selector:
    app: gatewayserver
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8072
      targetPort: 8072